export RK_PACKAGE_FILE_AB=rk3588-package-file-ab-one-rootfs
export RK_MISC=blank-misc.img
export RK_PARAMETER=parameter-ab-firefly-one-rootfs.txt
export RK_CFG_RECOVERY=
export RK_USERDATA_DIR=userdata_empty
export RK_USERDATA_FS_TYPE=ext4
export RK_USERDATA_PARTITION_SIZE=40M
export FIREFLY_RESIZE_ROOTFS_PARTITION="disabled"
export RK_UBOOT_DEFCONFIG_FRAGMENT="firefly-linux.config firefly-linux-ab.config"
